version: "3.3"
services:
    # db:
    #     image: postgres
    #     environment:
    #         POSTGRES_DB: postgres
    #         POSTGRES_PASSWORD: postgres
    #         POSTGRES_USER: postgres
    #     ports:
    #         - 5432:5432
    app:
        image: node:16
        ports:
            - 3000:3000
        build: .
volumes:
    postgres: